/**
 * Domain error codes for the API error contract.
 * Maps to tRPC error codes and HTTP statuses per api-contracts.md §4.
 */
export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_DOMAIN: 'INVALID_DOMAIN',
  SSH_CONNECTION_FAILED: 'SSH_CONNECTION_FAILED',
  SSH_AUTH_FAILED: 'SSH_AUTH_FAILED',
  SSH_COMMAND_FAILED: 'SSH_COMMAND_FAILED',
  SSH_KEY_DEPLOYMENT_FAILED: 'SSH_KEY_DEPLOYMENT_FAILED',
  INCOMPATIBLE_SERVER: 'INCOMPATIBLE_SERVER',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  DEPLOYMENT_FAILED: 'DEPLOYMENT_FAILED',
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
  CERTIFICATE_FAILED: 'CERTIFICATE_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  TIER_LIMIT_EXCEEDED: 'TIER_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
